### ISSUE TITLE
Wrong version in homebrew -> 7.4.4

### ISSUE THREAD

**Issue by zsoltjandzso** [Pavo-IM/ocbuilder#1]
<img width="595" alt="Screenshot 2020-09-13 at 20 18 54" src="https://user-images.githubusercontent.com/54944426/93025455-639db680-f5fe-11ea-8d96-33aa1727b2dd.png">

:)

**Comment by Pavo-IM** [comment]
You need to get ahold of [yurikoles](https://github.com/yurikoles), he is the one that made the Homebrew cast. Nothing to do with this repo.

**Comment by zsoltjandzso** [comment]
Are you sure?

<img width="884" alt="Screenshot 2020-09-13 at 21 59 13" src="https://user-images.githubusercontent.com/54944426/93027346-67d0d080-f60c-11ea-90fb-37d0c851fa5b.png">

**Comment by Pavo-IM** [comment]
Yes, he maintains the ocbuilder Homebrew [cast](https://github.com/yurikoles/homebrew-yurikoles/blob/master/Casks/ocbuilder.rb).

**Comment by earlthesquirrel** [comment]
I have same issue (I just opened an issue with Yurikoles.
