### ISSUE TITLE
Still issue is exist in ocbuilder.app v 2.5

### ISSUE THREAD

**Issue by ameenjuz** [Pavo-IM/ocbuilder#1]
still bug exist into ocbuilder.app v2.5
AppleSupportPkg repo stuck during build  I waited one hour but no luck
please fix this bug

**Comment by errorexists** [comment]
try install xcode with command line tools

**Comment by ameenjuz** [comment]
I already installed Xcode with command line tools

**Comment by Ahmotb** [comment]
hi ameenjuz . 
to fix the problem , just open terminal and but your email of the github and user like this
--
git config --global user.email XXXX@gmail.com
git config --global user.name AXXX
--
enjoy man

**Comment by Ahmotb** [comment]
Copying compiled products into EFI Structure folder in /Users/ahmed/Desktop/oc/03/OCBuilder_Completed...

All Done!...

**Comment by errorexists** [comment]
new update available

**Comment by Pavo-IM** [comment]
Issue has be resolved.
