### ISSUE TITLE
Panic when creating EFI

### ISSUE THREAD

**Issue by joostiphone** [Pavo-IM/ocbuilder#11]
I'm getting a panic when the build is proceeding (selection of 'release' and 'with kexts'). Can you please advise? Thank you.

`mp_kdp_enter() timed-out on cpu 7, NMI-ing
mp_kdp_enter() NMI pending on cpus: 0 5
mp_kdp_enter() timed-out during locked wait after NMI;expected 8 acks but received 7 after 13164405 loops in 1800000000 ticks
panic(cpu 7 caller 0xffffff80003c9811): "IPI timeout, unresponsive CPU bitmap: 0x20, NMIPI acks: 0x0, now: 0x0, deadline: 1343480369755, pre-NMIPI time: 0x138cdab9300, current: 0x138eb78f8d1, global: 1"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.50.5/osfmk/x86_64/pmap.c:2892
Backtrace (CPU 7), Frame : Return Address
0xffffffc101533620 : 0xffffff80002bd66d mach_kernel : _handle_debugger_trap + 0x3dd
0xffffffc101533670 : 0xffffff8000400073 mach_kernel : _kdp_i386_trap + 0x143
0xffffffc1015336b0 : 0xffffff80003f06aa mach_kernel : _kernel_trap + 0x55a
0xffffffc101533700 : 0xffffff8000262a2f mach_kernel : _return_from_trap + 0xff
0xffffffc101533720 : 0xffffff80002bcf0d mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffc101533840 : 0xffffff80002bd1f8 mach_kernel : _panic_trap_to_debugger + 0x268
0xffffffc1015338b0 : 0xffffff8000abfe1a mach_kernel : _panic + 0x54
0xffffffc101533920 : 0xffffff80003c9811 mach_kernel : _pmap_flush_tlbs + 0x7a1
0xffffffc1015339e0 : 0xffffff80003cf69f mach_kernel : _pmap_remove_range + 0x38f
0xffffffc101533ac0 : 0xffffff80003d0456 mach_kernel : _pmap_remove_options + 0x1f6
0xffffffc101533b20 : 0xffffff800035d4d5 mach_kernel : _vm_map_remove + 0x725
0xffffffc101533c70 : 0xffffff800035ce23 mach_kernel : _vm_map_remove + 0x73
0xffffffc101533ca0 : 0xffffff80003561f1 mach_kernel : _kmem_free + 0x71
0xffffffc101533cd0 : 0xffffff80009a3ed1 mach_kernel : __ZN11OSSerialize4freeEv + 0x21
0xffffffc101533cf0 : 0xffffff8000a4f11e mach_kernel : _is_io_registry_entry_get_properties_bin_buf + 0x1ae
0xffffffc101533d60 : 0xffffff80003adcd3 mach_kernel : _iokit_server_routine + 0x6ff3
0xffffffc101533d90 : 0xffffff80002c2d77 mach_kernel : _ipc_kobject_server + 0x337
0xffffffc101533e00 : 0xffffff80002995d5 mach_kernel : _ipc_kmsg_send + 0x115
0xffffffc101533e60 : 0xffffff80002b0b82 mach_kernel : _mach_msg_overwrite_trap + 0x2d2
0xffffffc101533ef0 : 0xffffff80003d4823 mach_kernel : _mach_call_munger64 + 0x273
0xffffffc101533fa0 : 0xffffff8000263216 mach_kernel : _hndl_mach_scall64 + 0x16

Process name corresponding to current thread: diskutil
Boot args: keepsyms=1 dart=0 debug=0x100 agdpmod=pikera alcid=11 shikigva=80 igfxfw=2

Mac OS version:
20B5022a

Kernel version:
Darwin Kernel Version 20.1.0: Thu Oct 29 05:35:40 PDT 2020; root:xnu-7195.50.5~4/RELEASE_X86_64
Kernel UUID: 0FC1EF69-BB5B-336F-B8FB-C1121939CE17
KernelCache slide: 0x0000000000000000
KernelCache base:  0xffffff8000200000
Kernel slide:      0x0000000000010000
Kernel text base:  0xffffff8000210000
__HIB  text base: 0xffffff8000100000
System model name: iMac19,1 (Mac-AA95B1DDAB278B95)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 1344980875171
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000139271b79c2
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000009d65c1f69c 0x0000000000000000

`

**Comment by Pavo-IM** [comment]
Just ran Release with kext and had no issues, this seems more to your system specifically how you have your configuration setup for memory mapping. Not a OCBuilder application issue.
