### ISSUE TITLE
NVMeFix

### ISSUE THREAD

**Issue by tmbt78** [Pavo-IM/ocbuilder#12]
Hello,
i would like to suggest the devs to include the kext in object because it is quite usefull when you've a laptop with an NVMe drive to improve power management. It has been developed by Acidanthera and it depends on Lilu.kext to be build.
Here is the link to the project : 
https://github.com/acidanthera/NVMeFix 

Thanks
Mattia

**Comment by Pavo-IM** [comment]
Added 7.0.6
