### ISSUE TITLE
Failing with reference to ARM?

### ISSUE THREAD

**Issue by DWomack** [Pavo-IM/ocbuilder#12]
Cloning into 'UDK'...
remote: Enumerating objects: 8763, done.
remote: Counting objects: 100% (8763/8763), done.
remote: Compressing objects: 100% (7629/7629), done.
remote: Total 8763 (delta 2553), reused 2535 (delta 975), pack-reused 0
Receiving objects: 100% (8763/8763), 14.08 MiB | 7.24 MiB/s, done.
Resolving deltas: 100% (2553/2553), done.
Updating files: 100% (7582/7582), done.
Submodule 'SoftFloat' (https://github.com/ucb-bar/berkeley-softfloat-3.git) registered for path 'ArmPkg/Library/ArmSoftFloatLib/berkeley-softfloat-3'
Submodule 'BaseTools/Source/C/BrotliCompress/brotli' (https://github.com/google/brotli) registered for path 'BaseTools/Source/C/BrotliCompress/brotli'
Submodule 'CryptoPkg/Library/OpensslLib/openssl' (https://github.com/openssl/openssl) registered for path 'CryptoPkg/Library/OpensslLib/openssl'
Submodule 'MdeModulePkg/Library/BrotliCustomDecompressLib/brotli' (https://github.com/google/brotli) registered for path 'MdeModulePkg/Library/BrotliCustomDecompressLib/brotli'
Submodule 'MdeModulePkg/Universal/RegularExpressionDxe/oniguruma' (https://github.com/kkos/oniguruma) registered for path 'MdeModulePkg/Universal/RegularExpressionDxe/oniguruma'
Submodule 'UnitTestFrameworkPkg/Library/CmockaLib/cmocka' (https://git.cryptomilk.org/projects/cmocka.git) registered for path 'UnitTestFrameworkPkg/Library/CmockaLib/cmocka'
Cloning into '/private/tmp/OCBuilder_Clone/OpenCorePkg/UDK/ArmPkg/Library/ArmSoftFloatLib/berkeley-softfloat-3'...
Cloning into '/private/tmp/OCBuilder_Clone/OpenCorePkg/UDK/BaseTools/Source/C/BrotliCompress/brotli'...
Cloning into '/private/tmp/OCBuilder_Clone/OpenCorePkg/UDK/CryptoPkg/Library/OpensslLib/openssl'...
Cloning into '/private/tmp/OCBuilder_Clone/OpenCorePkg/UDK/MdeModulePkg/Library/BrotliCustomDecompressLib/brotli'...
Cloning into '/private/tmp/OCBuilder_Clone/OpenCorePkg/UDK/MdeModulePkg/Universal/RegularExpressionDxe/oniguruma'...
Cloning into '/private/tmp/OCBuilder_Clone/OpenCorePkg/UDK/UnitTestFrameworkPkg/Library/CmockaLib/cmocka'...
fatal: unable to access 'https://git.cryptomilk.org/projects/cmocka.git/': Failed to connect to git.cryptomilk.org port 443: Connection refused
fatal: clone of 'https://git.cryptomilk.org/projects/cmocka.git' into submodule path '/private/tmp/OCBuilder_Clone/OpenCorePkg/UDK/UnitTestFrameworkPkg/Library/CmockaLib/cmocka' failed
Failed to clone 'UnitTestFrameworkPkg/Library/CmockaLib/cmocka'. Retry scheduled
Cloning into '/private/tmp/OCBuilder_Clone/OpenCorePkg/UDK/UnitTestFrameworkPkg/Library/CmockaLib/cmocka'...
fatal: unable to access 'https://git.cryptomilk.org/projects/cmocka.git/': Failed to connect to git.cryptomilk.org port 443: Connection refused
fatal: clone of 'https://git.cryptomilk.org/projects/cmocka.git' into submodule path '/private/tmp/OCBuilder_Clone/OpenCorePkg/UDK/UnitTestFrameworkPkg/Library/CmockaLib/cmocka' failed

**Comment by Pavo-IM** [comment]
Working fine here, check closed issues for troubleshooting steps.
