### ISSUE TITLE
OCBuilder can't find Xcode

### ISSUE THREAD

**Issue by cstrouse** [Pavo-IM/ocbuilder#13]
I have the command line tools installed (for Homebrew) and a full Xcode install but OCBuilder says that Xcode isn't installed.

```bash
casey@caseys-MacPro ~ % /Applications/OCBuilder.app/Contents/MacOS/OCBuilder
Cloning into 'Lilu'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 3833 (delta 49), reused 45 (delta 18), pack-reused 3744
Receiving objects: 100% (3833/3833), 4.25 MiB | 3.90 MiB/s, done.
Resolving deltas: 100% (2279/2279), done.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

<img width="848" alt="image" src="https://user-images.githubusercontent.com/849044/77579142-0dde2200-6e97-11ea-9c9e-99703e6cf098.png">

**Comment by Pavo-IM** [comment]
You can not use the command line tools from Home-brew. You must open Xcode and go to Preferences and go to Locations tab and elect the Xcode built-in commandline tools.

![Screenshot 2020-03-25 16 20 56](https://user-images.githubusercontent.com/33814640/77581757-ac2cb080-6eb4-11ea-8de7-4a1474f61b93.png)

**Comment by cstrouse** [comment]
Thanks. That got things working.
