### ISSUE TITLE
version 7.5.5

### ISSUE THREAD

**Issue by kimberwhitehead** [Pavo-IM/ocbuilder#13]
cannot get further than cloning issue Lilu, it is still broken.
<img width="1294" alt="Screenshot 2020-11-21 at 19 30 17" src="https://user-images.githubusercontent.com/59763601/99885887-017db500-2c30-11eb-9c0d-b793f2290188.png">

**Comment by Pavo-IM** [comment]
Read closed issues for troubleshooting steps. The app is working
![Screen Shot 2020-11-21 at 2 47 25 PM](https://user-images.githubusercontent.com/33814640/99886189-9bca0280-2c08-11eb-8b73-6237b71489f5.png)
