### ISSUE TITLE
ocbuilder won't build AtherosE2200Ethernet.kext correctly.

### ISSUE THREAD

**Issue by tecnicasopr** [Pavo-IM/ocbuilder#14]
After using ocbuilder to build latest OpenCore my system doesn't boot. When investigating the problem I found out that the culprit was AtherosE2200Ethernet.kext Then I downloaded the latest version built and uploaded by Mieze from a Post where he publish his kext, and then I was able to boot again. What is weird is that when downloading the repo myself and then building it with xcode, it gives me the same negative result: it won't boot. Also it's being built incorrectly when using the kext building tool within hackintool. 
![IMG_20201208_101028](https://user-images.githubusercontent.com/44104841/101512469-08ebd080-3949-11eb-977f-eba383a524bd.jpg)

**Comment by Pavo-IM** [comment]
This is not a OCBuilder issue, this is a repo issue. OCBuilder clones the repo in its current state and compiles it for Release configuration. If the code in that repo isn't compilable or builds a binary that has operating issues, that is an issue for that product, not OCBuilder.

**Comment by tecnicasopr** [comment]
I agree with you. But people who depend on this kext can end of with an
unbootable system after building OpenCore with ocbuilder. I tried to warn
him on his tread but he hasn't respond yet. I suspect the problem started
when he merged. Thanks for taking time to answer me. I appreciate that.

**Comment by Pavo-IM** [comment]
Agreed, but thats all my app is, a builder nothing more and nothing less. Who maintains the code for that repo is responsible to make it buildable. I can temporarily remove that kext from being built, but thats as far as I can go.

**Comment by tecnicasopr** [comment]
Thanks.
