### ISSUE TITLE
The release version have a bug 

### ISSUE THREAD

**Issue by LightYagami28** [Pavo-IM/ocbuilder#15]
https://user-images.githubusercontent.com/71499553/102708968-a084e380-42a6-11eb-8863-7e777a615c92.mov

**Comment by moppi4483** [comment]
Hello,

make sure you installed Xcode into `/Application/Xcode`.

Then execute the following command `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by LightYagami28** [comment]
Hello,

I followed your advice and now it works greats.

Thanks for Your support
