### ISSUE TITLE
Fails compiling Opencore 0.6.6, latest release.

### ISSUE THREAD

**Issue by mrgooge** [Pavo-IM/ocbuilder#17]
I can't seem to get a completed compile of the latest Opencore 0.6.6, just fails (never finishes) around 3/4 of the way through and the "Build" button just becomes active... Is it me, or is it something with latest Opencore 0.6.6?

**Comment by errorexists** [comment]
try this method to see what the issues are an then you post the info 
https://youtu.be/Ahy4MgRJsdE

**Comment by mrgooge** [comment]
So this is the result (using the method from youtube)  in my terminal window: 

- Done -
Build end time: 18:03:51, Jan.25 2021
Build total time: 00:00:24

64+0 records in
64+0 records out
64 bytes transferred in 0.000653 secs (98005 bytes/sec)
64+0 records in
64+0 records out
64 bytes transferred in 0.000605 secs (105808 bytes/sec)
cp: HdaCodecDump.efi: No such file or directory

And it does not create the folder on my Desktop.

---
and it just hangs there.

Thanks

**Comment by Pavo-IM** [comment]
Fixed in the latest version

**Comment by mrgooge** [comment]
Thank you very much, it works great!
