### ISSUE TITLE
7.6.0 not building the kexts

### ISSUE THREAD

**Issue by dehjomz** [Pavo-IM/ocbuilder#18]
Hello,

I am not sure if I'm doing something incorrect, but the latest version of OCBuilder (7.6.0) doesn't seem to build the kexts.  It builds the OC beta (0.6.7) if I deselect "With kexts" but if I select "With Kexts" the process stops at Lilu, and I am not sure the error message or how to debug.

**Comment by Pavo-IM** [comment]
Read some of the troubleshooting steps in the closed issues section, because I just ran it and its compiling all the kexts and OC just fine.
