### ISSUE TITLE
documentation : brew cask install ... not working any longer

### ISSUE THREAD

**Issue by andistern** [Pavo-IM/ocbuilder#19]
either use
`brew install ocbuilder`
or
`brew install --cask ocbuilder`
... and check for latest version, as 7.5.6 is not able to successfully update OC ...
```
brew cask install ocbuilder
Error: Unknown command: cask

```
Ex. 1
```
brew install ocbuilder
==> Downloading https://github.com/Pavo-IM/ocbuilder/releases/download/7.5.6/OCBuilder.app.zip

```
Ex. 2
```
brew install --cask ocbuilder 
==> Downloading https://github.com/Pavo-IM/ocbuilder/releases/download/7.5.6/OCBuilder.app.zip

```

**Comment by Pavo-IM** [comment]
the dev that was maintaining the new cast has stopped updating it, I will remove it from the documentation. Thanks for reminding me.

**Comment by andistern** [comment]
jurikoles just updated : [https://github.com/yurikoles/homebrew-yurikoles/commit/fba1495220288501c4c068f6c72f48ce3a6f2e66](url)
