### ISSUE TITLE
OCBuilder Issues v 2.7

### ISSUE THREAD

**Issue by ameenjuz** [Pavo-IM/ocbuilder#2]
Ocbuilder.app v 2.7 once again stuck Cloning AppleSupportPkg SupportPkgs into UDK during compiling
please fix this issue

**Comment by MacProDude** [comment]
Works fine here.

**Comment by ameenjuz** [comment]
I have stuck Cloning AppleSupportPkg SupportPkgs into UDK since one hour but didn't appear completed or done

**Comment by MacProDude** [comment]
You clearly have a missing component for the app to run.

**Comment by ameenjuz** [comment]
I already installed Xcode 10.3 with command line tools 
about in this component are you saying?
Installing Required NASM tool
Installing Required ndisasm tool
Install Required MTOC tool
Install Required MTOC.NEW tool

**Comment by MacProDude** [comment]
Yes NASM and MTOC, i had an issue on another machine running the app as it wasn't installing these, i had to install them manually.

**Comment by errorexists** [comment]
are you sure your on 2.7 as this worked just fine for me

**Comment by ameenjuz** [comment]
I successfully compiled 2 two days ago now I have issue 
how to install NASM and Mtoc manually please provide me link one by one

**Comment by MacProDude** [comment]
The way i did this was to download the OpenCore Frontend from Github and then run the macbuild.tool in terminal if they are not installed macbuild will prompt you to install them. 


https://github.com/acidanthera/OpenCorePkg

**Comment by ameenjuz** [comment]
Successfully compiled on Ocbuilder.app v2.6 without any components
Ocbuilder.app v2.7 still has bug

**Comment by Pavo-IM** [comment]
Run the app from terminal and give me an output of where it errors please.

**Comment by jcastro** [comment]
I think I'm having same probblem with 2.7, but it's stopping at the beginning. Here's the terminal log
`Jonatans-MBP:OpenCorePkg jonatan$ /Applications/OCBuilder.app/Contents/MacOS/OCBuilder 
objc[813]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8ef6b3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x107efdf50). One of the two will be used. Which one is undefined.
Password:Cloning into 'Lilu'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (134/134), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 3690 (delta 69), reused 70 (delta 36), pack-reused 3556
Receiving objects: 100% (3690/3690), 4.25 MiB | 4.54 MiB/s, done.
Resolving deltas: 100% (2148/2148), done.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

**Comment by Pavo-IM** [comment]
> I think I'm having same probblem with 2.7, but it's stopping at the beginning. Here's the terminal log
> 
> > Jonatans-MBP:OpenCorePkg jonatan$ /Applications/OCBuilder.app/Contents/MacOS/OCBuilder
> > objc[813]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8ef6b3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x107efdf50). One of the two will be used. Which one is undefined.
> > Password:Cloning into 'Lilu'...
> > remote: Enumerating objects: 134, done.
> > remote: Counting objects: 100% (134/134), done.
> > remote: Compressing objects: 100% (98/98), done.
> > remote: Total 3690 (delta 69), reused 70 (delta 36), pack-reused 3556
> > Receiving objects: 100% (3690/3690), 4.25 MiB | 4.54 MiB/s, done.
> > Resolving deltas: 100% (2148/2148), done.
> > xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

You need to open Xcode and go to Preferences > Locations Tab > Select a Command Line Tools before running the app. After doing that, run the app from terminal again and see if there is any errors.

**Comment by jcastro** [comment]
Thanks @Pavo-IM, that made it!
