### ISSUE TITLE
Error building OC, as of 3/24

### ISSUE THREAD

**Issue by mrgooge** [Pavo-IM/ocbuilder#20]
Build does not complete, just stops. Getting the following when building from terminal:

- Done -
Build end time: 14:16:17, Mar.24 2021
Build total time: 00:00:22

64+0 records in
64+0 records out
64 bytes transferred in 0.000615 secs (104045 bytes/sec)
64+0 records in
64+0 records out
64 bytes transferred in 0.000607 secs (105434 bytes/sec)
cp: VerifyMsrE2.efi: No such file or directory

**Comment by errorexists** [comment]
do this to find the issues with oc builder https://www.youtube.com/watch?v=Ahy4MgRJsdE

**Comment by mrgooge** [comment]
Yes, I did that see above, failing on VerifyMsrE2.efi , looks like Opencore developers don't use it anymore... I just saw this from their changelog: _Replaced VerifyMsrE2 with ControlMsrE2 also allowing unlock on some firmwares_



    Done -
    Build end time: 14:16:17, Mar.24 2021
    Build total time: 00:00:22

64+0 records in
64+0 records out
64 bytes transferred in 0.000615 secs (104045 bytes/sec)
64+0 records in
64+0 records out
64 bytes transferred in 0.000607 secs (105434 bytes/sec)
**cp: VerifyMsrE2.efi: No such file or directory**
