### ISSUE TITLE
The network is slow

### ISSUE THREAD

**Issue by scalpelxxx** [Pavo-IM/ocbuilder#22]
I found that this is downloading information through git, the system's proxy does not work, is there a way to give this application a proxy network.

**Comment by Pavo-IM** [comment]
The application uses the system's network configuration. If your system proxy is slow, nothing I can do about that.

**Comment by scalpelxxx** [comment]
Restrictions on github where I am .Now I have solved the problem. After turning on the agent, the following operations were performed.
![截屏2020-06-26 下午12 47 40](https://user-images.githubusercontent.com/64622405/85821569-8365d100-b7ab-11ea-8bdf-b49540dfcf88.png)
