### ISSUE TITLE
OpenCore Build file not saved anywhere

### ISSUE THREAD

**Issue by fayyaz42** [Pavo-IM/ocbuilder#23]

**Comment by fayyaz42** [comment]
open core build is working but No file is saved at Desktop

**Comment by Pavo-IM** [comment]
You have to select where it is being saved, double check your selection.

**Comment by SvenPe** [comment]
I do have the same problem, even when I select a folder. 
It also doesn't matter which folder I select (new one, Downloads, Desktop)
