### ISSUE TITLE
Freezing at NASM

### ISSUE THREAD

**Issue by BoddhC** [Pavo-IM/ocbuilder#24]
Hi,

It is freezing when it gets to "NASM is missing!, Installing...

Thank you for this app!

**Comment by Pavo-IM** [comment]
Need to see a error log, because it working normally here.

**Comment by abidshahriar** [comment]
same issue.

**Comment by vin-d** [comment]
Same issue, where is the log file ? there's nothing in ~/Library/Logs

I don't really understand i've done the process 5 or 6 times and I always had the same proble as described by @BoddhC, Then I've quit OCBuilder to reopen it, run it again, and then this time I got the damn Catalina  [security prompt](https://ibb.co/524Hvzq) that never came before. Then I had two more prompts asking for password.

Now either there is a bug in the security prompt routine of macos, either it's in the macOS window server and the security prompt had open  without putting it in front of all my other windows (I have several dozen open).

@BoddhC  try to quit quit OCBuilder close every other window to have a clutter free desktop and retry.
If you still don't see the security popup, go in System Preferences > Security & Privacy in tab Privacy, there in the list check in Automation if OCBuilder.app is listed and the checkbox is checked for "System Events.app"

**Comment by Pavo-IM** [comment]
There should be only two password prompts after your initial opening of the app. Those password prompts are to install nasm and mtoc into `/usr/local/bin` directory. If you would open the app executable inside the contents of the app and run that executable in terminal it will give you the error if there is one. Please provide the errors.
