### ISSUE TITLE
Consider Adding Functionality to Display the Commit Version that was Built by the Tool

### ISSUE THREAD

**Issue by dehjomz** [Pavo-IM/ocbuilder#25]
Hello. Cheers for this excellent tool.  I'm wondering if it's possible to add functionality to note to the user which commit was pulled from the repos and compiled by the tool?  Whether in a log file or displayed in the GUI? (Or give the user the option to enable/disable showing this info?)  

Given that opencore is rapidly changing now since Apple introduced so many changes to Big Sur, it is very helpful to know what commit has been built.  Some of the recent commits weren't working properly (e.g., recently we had to add vsmcgen=1 to boot-args to properly load the installer.  This has since been fixed).  

Just a thought.  Thank you so much for this tool.

**Comment by Pavo-IM** [comment]
The app always builds the latest commit from the respectful repo, at the time of you using the app. That was the purpose of the app in the first place, if you want to know what that commit is, you can check the repo yourself to see what you are about to build on.

**Comment by dehjomz** [comment]
Okay. I suppose I could modify the source code on my own and display that info on the screen. 

Thank you though!!
