### ISSUE TITLE
OCBuilder stops working

### ISSUE THREAD

**Issue by L0rdLogan** [Pavo-IM/ocbuilder#26]
Hi.

I'm having a weird issue with OCbuilder on my system, the build process with stop after it says 'Compiling the latest commited Debug version of Lilu'

building it without Kexts works fine.

OS: Catalina 10.5.5

**Comment by Pavo-IM** [comment]
Run the app executable in terminal and look for errors, upload a pic of the error because I can not replicate this issue.
