### ISSUE TITLE
stopped working at 'NASM is missing' 

### ISSUE THREAD

**Issue by abidshahriar** [Pavo-IM/ocbuilder#29]
![Screen Shot 2020-07-27 at 10 08 42 AM](https://user-images.githubusercontent.com/64680295/88502937-e12b4a00-cff1-11ea-8218-a681e23a0bff.png)

**Comment by Pavo-IM** [comment]
The error is telling you that the user that you are logged in as does not have sudoer (root ) access, you must use an account that has root access.

**Comment by abidshahriar** [comment]
thought so....this is an admin account with administrative privilege however maybe someway the sudoers file is corrupted.
