### ISSUE TITLE
OCBuilder 2.9 Issues

### ISSUE THREAD

**Issue by BeanieBen9990** [Pavo-IM/ocbuilder#3]
OCBuilder 2.9 Isn't compiling HibernationFixup correctly...

Errors out with:

** BUILD FAILED **

The following build commands failed:
	CompileC build/HibernationFixup.build/Release/HibernationFixup.build/Objects-normal/x86_64/gmtime.o HibernationFixup/gmtime.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Any help?

**Comment by Pavo-IM** [comment]
Compiling fine for me, just tried.

**Comment by BeanieBen9990** [comment]
Well I guess I can’t argue with that. It might be something as simple as a missing prerequisite or a reboot. Thanks anyway! I’ll keep the issue open until I get it working, in case someone else has the same problem.

**Comment by Pavo-IM** [comment]
All prerequisites get installed by the app besides Xcode. But if its compiling the other kexts before getting to HibernationFixup then I don't see anyway that it could be your system. Maybe an issue with the repo at the time of you building. Try again and report back please.

**Comment by fangf2018** [comment]
Cloning UDK Repo into OpenCoreShell...  To break off  

The three time

**Comment by evchibo** [comment]
The builder stalls at `Cloning UDK Repo into OpenCoreShell....` the build button becomes active and nothing happens thereafter

**Comment by Pavo-IM** [comment]
You need to run the app in terminal and post errors that you are getting. Closing the issue until error logs are provided.
