### ISSUE TITLE
cannot be download with kexts

### ISSUE THREAD

**Issue by jinhaozcp** [Pavo-IM/ocbuilder#30]
The latest version, selected kexts, cannot be downloaded. What is the reason?
![WX20200727-202703](https://user-images.githubusercontent.com/32815759/88541591-dc52a000-cfc9-11ea-801b-7b0fca69a806.png)

**Comment by Pavo-IM** [comment]
You need to right click on the app go to Contents/MacOS and open the binary in terminal and see what the error you are getting.

**Comment by Pavo-IM** [comment]
It also looks like if you are using Xcode beta 12 it does not work in building. You must use Xcode 11.

**Comment by jinhaozcp** [comment]
Thank you! already solved! Need to drag the OCB to the utility.
![WX20200727-211106](https://user-images.githubusercontent.com/32815759/88545692-2dfe2900-cfd0-11ea-97a1-a6503dea981b.png)
