### ISSUE TITLE
OpenCore Builder 7.4.4

### ISSUE THREAD

**Issue by nayga73** [Pavo-IM/ocbuilder#35]
![Screenshot 2020-08-03 at 23 09 45](https://user-images.githubusercontent.com/69173370/89233063-bdaf6300-d5e0-11ea-9240-3a8fd2e52552.png)

Stuck at NASM is Missing,Installing.
Closed the app down on numerous occasions, machine rebooted several times, same outcome each time :(
Using a HP Probook 445 G5 i5 Kaby Lake-R
Xcode is already installed and T's and C's have been accepted already.

nayga73

**Comment by Pavo-IM** [comment]
Hoiw about look at previously closed issues that are related that already have troubleshooting steps.
