### ISSUE TITLE
Latest build does not boot

### ISSUE THREAD

**Issue by SavageAUS** [Pavo-IM/ocbuilder#37]
I’ve tried building twice today 01/sept/2020 and both times the build will not boot.
Not sure if this is an OCBuilder issue or an OC issue.

**Comment by Pavo-IM** [comment]
Agreed, OC has made some changes to the way they build and I have to take sometime to figure out what has changed. A update will be coming soon.

**Comment by Pavo-IM** [comment]
@SavageAUS Can you test this build? I have tested it and it seems the files it produces is bootable now.
[OCBuilder.zip](https://github.com/Pavo-IM/ocbuilder/files/5159095/OCBuilder.zip)

**Comment by SavageAUS** [comment]
Build and boot both successful.
Great work.

**Comment by Pavo-IM** [comment]
Ok cool, I'll push newest code and you should be able to update from within your current version of the app to the latest in about 10 minutes.

**Comment by dehjomz** [comment]
Was having the same problem but newest build fixes it.  Good work!
