### ISSUE TITLE
Latest commited Release

### ISSUE THREAD

**Issue by webfalter** [Pavo-IM/ocbuilder#4]
https://github.com/acidanthera/WhateverGreen does not build 1.3.4 but 1.3.3?

**Comment by errorexists** [comment]
try this https://onedrive.live.com/?authkey=%21ALwI55RytlXeZ68&cid=FE4038DA929BFB23&id=FE4038DA929BFB23%21493024&parId=FE4038DA929BFB23%21455095&action=locate

**Comment by webfalter** [comment]
Thank you, wanted to know why. I also get it built with XCode

**Comment by Pavo-IM** [comment]
OCBuilder builds whatever is on the latest commit of the repos, so whenever you used OCBuilder to compile the repos it depends on the repos.
