### ISSUE TITLE
OCBuilder 7.5.3 does not build and even crashed [Big Sur Beta 8]

### ISSUE THREAD

**Issue by AlexDanDuna** [Pavo-IM/ocbuilder#4]
I keep trying to build OC (Debug / Release) with OCBuilder 7.5.3 (and even 7.5.1 before that), but Build simply does not work: it displays it's downloading latest Lilu from repository, the status bar thingy at the bottom moves for a little left-to-right-to-left and then it just stops (the status bar and the log displays nothing anymore).. The Stop button becomes greyed out and I can Build again, but with same result.

I tried building from source thinking it might work. I chose 10.15 as deployment target and built using Product -> Build for -> Running from Xcode 12.0. I got a crash after trying to press Build in OCBuilder a few times:

https://pastebin.com/mg19iPNm

EDIT: Please edit the title.. I meant it is not building the OpenCore stuff, not that it fails build in Xcode.

**Comment by errorexists** [comment]
just ran it an runs fine you can test in terminal to see where is stops for issues 
https://www.youtube.com/watch?v=Ahy4MgRJsdE

**Comment by Pavo-IM** [comment]
Have no clue what you are talking about, its working perfectly fine here. Run the app from terminal and watch for errors.
You can only compile the app from source if you have an actual Apple Developer account.
![Screen Shot 2020-09-26 at 11 46 30 AM](https://user-images.githubusercontent.com/33814640/94344536-181bdd00-ffee-11ea-80f9-4306417b3fb0.png)

**Comment by AlexDanDuna** [comment]
Thank you for your reply. Watching from console really helped..  it was getting stuck because Command Line tools were selected or something (I am not VERY familiar with Xcode). This probably happened because those tools got installed when I installed Homebrew (after Xcode). However, I had tried OCBuilder in between installing Homebrew and it still was getting stuck most of the time (but one or two times it worked).. maybe back then it worked because I had renamed my coexisting Xcode Beta to Xcode.

![Screenshot 2020-09-28 at 11 29 41](https://user-images.githubusercontent.com/15891467/94408855-3c7cd400-012a-11eb-9012-53e80106fae2.png)

**SOLUTION:**
In any case, I applied [the fix here](https://github.com/nodejs/node-gyp/issues/569) to switch Xcode back to full xcode instead of command line tools and now it is working fine: 
```
# Change the path if you installed Xcode somewhere else.

sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**SUGGESTION:**
Would it not be possible to show that error in OCBuilder's GUI?



As I side note, I was actually able to compile it with a personal account, too. Could you please explain why a developer account is needed? EDIT: I just noticed you might have wrongly interpreted my issue's title because of my very poor wording (which I mentioned should be changed in my OP since I cannot change it myself :) )

Thank you for your help and for sharing this App with us! :)

**Comment by Pavo-IM** [comment]
Please look at earlier closed issues and you will see what you need to do. The reason for the developer account is because of the Sparkle framework for updates.
