### ISSUE TITLE
Nvmefix.kext not buiilding

### ISSUE THREAD

**Issue by dehjomz** [Pavo-IM/ocbuilder#5]
Hi Pavo, thanks for this very wonderful tool.  I noticed that the current version of the tool (v7.5.3) doesn't build Nvmefix.kext from the Acidanthera repository... older versions of your tool used to build this kext.  I am wondering if you are aware, and if so, why you removed nvmefix.kext from the build?

Thanks!

**Comment by Pavo-IM** [comment]
Fixed in [694ef5a
](https://github.com/Pavo-IM/ocbuilder/commit/694ef5a34074de1cb021de208db261863987ad7d)
