### ISSUE TITLE
OCBuilder gets stuck at "Compiling the latest commited Debug version of Lilu..."

### ISSUE THREAD

**Issue by deathgrape** [Pavo-IM/ocbuilder#6]
Posting this in case it helps someone else- 
I got this error, so I ran OCBuilder via Terminal and it spat out this error:

error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Googling it, I found this solution:
https://github.com/nodejs/node-gyp/issues/569

Running this command in Terminal fixed it for me, and I was able to compile OpenCore successfully:
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

**Comment by Pavo-IM** [comment]
This is not OCBuilder related, as the instruction say. You have Xcode installed and fully running before using OCBuilder. https://github.com/Pavo-IM/ocbuilder#this-app-requires-the-full-xcode-app-installed-in-order-to-compile-the-source-you-also-must-agree-to-the-user-agreement-after-installing-xcode-app

**Comment by E-werd** [comment]
Your link is not the problem that @deathgrape is describing.  It is a problem, but not the same problem.  Do a fresh install of MacOS (I've seen this and told you as much with 10.14 and 10.15) and you will see this issue AFTER correcting what you've suggested.

**Comment by Pavo-IM** [comment]
Yes the info of what I linked is the problem, just done a fresh install of MacOS and installed Xcode freshly. You have to open Xcode and agree to the ToS (which mean fully running) before running the OCBuilder app. OCBuilder app finishes all requirements itself after that. If you have only installed Xcode but not opened it and agreed to the ToS, then OCBuilder can not use xcodebuild command from the system. It will require you to set the location of the Commandline Tools which is what agreeing to the ToS of Xcode does when you first start Xcode after install.
