### ISSUE TITLE
Support for building 32bit EFI (IA32)

### ISSUE THREAD

**Issue by Austcool-Walker** [Pavo-IM/ocbuilder#7]
In the next release is it possible for Mojave and below to support building 32bit EFI (IA32) on Mojave and below?

**Comment by Austcool-Walker** [comment]
https://gist.github.com/Austcool-Walker/cebf7934e7d00ae2c91c5cb206ac6ce3 I made a sample of a working build script for the Resources folder.

**Comment by Pavo-IM** [comment]
You are more than welcome to fork the repo, make changes to check for OS version and execute a new script for 32bit EFI and submit a pull request to merge it into the app. I will not be adding this myself, because 32bit is extremely old.
