### ISSUE TITLE
How to tell what's wrong?

### ISSUE THREAD

**Issue by DWomack** [Pavo-IM/ocbuilder#9]
I have been seeing this issue for some time.

When I open the program, I select Release, and then try to set destination for the folder.

Sometimes it works, other times it does not.  It seems to be stuck.  I can exit the program and restart it.  Sometimes it works and sometimes it does not.

Logging out and logging back in always seems to fix it.

I usually have the created folder dropped into the same folder on the desktop.  I zip the desktop folder and save it.  Then I clear the desktop folder ahead of the next time.

Can you make the target selection for the folder sticky?  ie: it will be used again until changed.

Thanks

Dennis

**Comment by Pavo-IM** [comment]
You seem to be the only user that is coming across this issue. Do you happen to have Desktop & Documents folder enabled under iCloud Drive options?

**Comment by DWomack** [comment]
I’ll check.  

I just got it to work again after shutting down FireFox

It has been doing this for many months. 

Is there a way to start it where I can see an error log?

I run it every morning and every evening.  

Thanks. 


Dennis

**Comment by Pavo-IM** [comment]
If you read some of the closed issues, you will see instructions on how to open the app and be able to see errors.

**Comment by DWomack** [comment]
With FireFox closed, I started OCbuilder and was able to select target for the directory.

I closed it and...

With FireFox open looking at GitHub...

I started OCbuilder again in Terminal...

2020-10-13 06:55:09.200 OCBuilder[10613:8587373] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'com.apple.view-bridge': Connection interrupted

This is running on a NUC10i7 with OC 0.59 and macOS 10.15.7 fully patched.

Hope this helps.


Dennis

**Comment by DWomack** [comment]
Problem and solution are repeatable...

2020-10-13 07:12:03.628 OCBuilder[26908:8640688] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'com.apple.view-bridge': Connection interrupted

I halted FireFox and it compiled.

Restarted FireFox and went to GitHub.  Started it in Terminal again with the result above.

Hope this helps.


Dennis

**Comment by Pavo-IM** [comment]
No clue, sounds like its a conflict with Firefox.

**Comment by amiralimahmoudi** [comment]
when i click on release and select destination folder and click run, it stuck and dont work
but when i select ia32 release ocbuilder start downloading
can you help me out here?

**Comment by errorexists** [comment]
@DWomack i have never had an issue with downloading from firefox so its possible your firefox is having other issues try reinstalling it an trying again 

@amiralimahmoudi you should move the app to the app folder then run it from there no wheres else is good to run it

**Comment by Pavo-IM** [comment]
I have tried to replicate this issue on multiple different systems and MacOS versions and have not been able to replicate it. Closing until multiple people have the same issue.

**Comment by DWomack** [comment]
Still having this issue.  Starting in Terminal does show there is a problem on occasion.  I think it is having an issue with other software open at the time it runs.  Sometimes it is FireFox sometimes others, but what?  Logging out the user and back in, always seems to let it run.  
Doing a little searching on the error, shows multiple people having the error with many different packages.
This link might be helpful...

https://developer.apple.com/forums/thread/104576

The problem seems to occur due to something in Apple's API model or how resources are handled.  One article referred to threading issues.

Now I know the work around is to logout and log back in.

Just thought you'd want to know.

Commenting here because that's the only way I know to message you.


Dennis

**Comment by errorexists** [comment]
@DWomack try to reinstall your system
